---
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Sofia
      - PASSWORD=PASSWOR
    volumes:
      - librespeed_conf:/config
    ports:
      - 80:80
    restart: unless-stopped

volumes:
  librespeed_conf: